//
//  TablePresenter.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol TablePresenterInterface
{
  func presentFetchedPost(response: Table.FetchPost.Response)
}

class TablePresenter: TablePresenterInterface
{
  var output: TableViewControllerInterface!

  
  // MARK: - Presentation logic
  
  func presentFetchedPost(response: Table.FetchPost.Response) {
    let posts = response.data.map { dic -> Post in
      return Post(
        id: dic["id"] as? Int ?? 0, userId: dic["userId"] as? Int ?? 0,
        title: dic["title"] as? String ?? "", body: dic["body"] as? String ?? ""
      )
    }
    
    let viewModel = Table.FetchPost.ViewModel(post: posts, errorMessage:response.errorMessage)
    output.displayFetchedPost( viewModel: viewModel )
  }
  
  //MARK: - private function
  
  
}
