//
//  TableModels.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Table
{
  struct FetchPost
  {
    struct Request
    {
    }
    struct Response
    {
      var isSuccess:Bool
      var errorMessage:String?
      var data:[[String:Any]]
    }
    struct ViewModel
    {
      var post:[Post]
      var errorMessage:String?
    }
  }
}
