//
//  TableInteractor.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Alamofire

protocol TableInteractorInterface
{
  func fetchPost(request: Table.FetchPost.Request)
}

class TableInteractor: TableInteractorInterface
{
  var output: TablePresenterInterface!
  
  // MARK: - Business logic
  
  func fetchPost(request: Table.FetchPost.Request) {
    Alamofire.request("http://jsonplaceholder.typicode.com/users/1/posts").responseJSON { [weak self] dataResponse in
      guard let s = self else {
        return
      }
      
      guard let postsData = dataResponse.result.value as? [[String:Any]], dataResponse.result.isSuccess else {
        let response = Table.FetchPost.Response(isSuccess: false, errorMessage: dataResponse.error?.localizedDescription, data: [])
        s.output.presentFetchedPost(response: response)
        return
      }
      
      let response = Table.FetchPost.Response(isSuccess: true, errorMessage: nil, data: postsData)
      
      s.output.presentFetchedPost(response: response)
    }
    
  }
  
}







