//
//  SettingPresenter.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingPresenterInterface
{
  func presentSomething(response: Setting.Something.Response)
}

class SettingPresenter: SettingPresenterInterface
{
  var output: SettingViewControllerInterface!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: Setting.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = Setting.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
