//
//  SettingRouter.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingRouterInterface
{
  func navigateToLogin()
}

class SettingRouter: SettingRouterInterface
{
  weak var viewController: SettingViewController!
  
  // MARK: - Navigation
  
  func navigateToLogin()
  {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let login = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
    let delegate = UIApplication.shared.delegate as! AppDelegate
    delegate.window?.rootViewController = login
  }
  
  // MARK: - Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router which scenes it can communicate with
    
    if segue.identifier == "ShowSomewhereScene" {
      passDataToSomewhereScene(segue: segue)
    }
  }
  
  func passDataToSomewhereScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router how to pass data to the next scene
    
    // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
    // someWhereViewController.output.name = viewController.output.name
  }
}
