//
//  SettingViewController.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingViewControllerInterface
{
  func displaySomething(viewModel: Setting.Something.ViewModel)
}

class SettingViewController: UITableViewController, SettingViewControllerInterface
{
  var output: SettingInteractorInterface!
  var router: SettingRouter!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    SettingConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: - Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = Setting.Something.Request()
    output.doSomething(request: request)
  }
  
  // MARK: - Display logic
  
  func displaySomething(viewModel: Setting.Something.ViewModel)
  {
    // NOTE: Display the result from the Presenter
    // nameTextField.text = viewModel.name
    
  }
  
  //MARK: - Datasource & Delegate
  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    router.navigateToLogin()
  }
}
