//
//  SettingConfigurator.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class SettingConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = SettingConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: SettingViewController)
  {
    let router = SettingRouter()
    router.viewController = viewController
    
    let presenter = SettingPresenter()
    presenter.output = viewController
    
    let interactor = SettingInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
