//
//  MapConfigurator.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

class MapConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = MapConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: MapViewController)
  {
    let router = MapRouter()
    router.viewController = viewController
    
    let presenter = MapPresenter()
    presenter.output = viewController
    
    let interactor = MapInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
