//
//  MapInteractor.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MapInteractorInterface
{
  func doSomething(request: Map.Something.Request)
}

class MapInteractor: MapInteractorInterface
{
  var output: MapPresenterInterface!
  var worker: MapWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Map.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = MapWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Map.Something.Response()
    output.presentSomething(response: response)
  }
}
