//
//  MapPresenter.swift
//  Base Project
//
//  Created by Saminos on 08/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MapPresenterInterface
{
  func presentSomething(response: Map.Something.Response)
}

class MapPresenter: MapPresenterInterface
{
  var output: MapViewControllerInterface!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: Map.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = Map.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
