//
//  LoginModels.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Login
{
  struct FetchUser
  {
    struct Request
    {
      var password:String?
      var email:String?
    }
    struct Response
    {
      var user:User?
      var isSuccess:Bool
      var errorMessage:String?
    }
    struct ViewModel
    {
      var user:User?
      var isSuccess:Bool
      var errorMessage:String?
    }
  }
}
