//
//  LoginPresenter.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginPresenterInterface
{
  func presentFetchedUser(response: Login.FetchUser.Response)
}

class LoginPresenter: LoginPresenterInterface
{
  var output: LoginViewControllerInterface!
  
  // MARK: - Presentation logic
  
  func presentFetchedUser(response: Login.FetchUser.Response)
  {
    
    let viewModel = Login.FetchUser.ViewModel(
      user: response.user, isSuccess: response.isSuccess, errorMessage: response.errorMessage
    )
    
    output.displayFetchedUser(viewModel: viewModel)
  }
}
