//
//  LoginRouter.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginRouterInterface
{
  func navigateToTab()
}

class LoginRouter: LoginRouterInterface
{
  weak var viewController: LoginViewController!
  
  // MARK: - Navigation
  
  func navigateToTab()
  {
    let tab = Storyboard.viewController(by: "TabViewController")
    viewController.show(tab, sender: nil)
  }
  
}
