//
//  LoginInteractor.swift
//  Base Project
//
//  Created by Saminos on 07/06/17.
//  Copyright (c) 2017 Flipbox. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Alamofire

protocol LoginInteractorInterface
{
  func login(request: Login.FetchUser.Request)
}

class LoginInteractor: LoginInteractorInterface
{
  var output: LoginPresenterInterface!
  var worker: LoginWorker!
  
  // MARK: - Business logic
  
  func login(request: Login.FetchUser.Request) {
    
    worker = LoginWorker()
    worker.login(request: request) { [weak self] response  in
      guard let s = self else { return }
      s.output.presentFetchedUser(response: response)
    }
    
  }
}
